// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUgrIcD0M7DhpBDoSIYppQTrwXFwPUbc',
    appId: '1:519139634593:web:1ad4cf90f13bb4e9de2fe0',
    messagingSenderId: '519139634593',
    projectId: 'ieee-cmsb-app',
    authDomain: 'ieee-cmsb-app.firebaseapp.com',
    storageBucket: 'ieee-cmsb-app.appspot.com',
    measurementId: 'G-HV66RNBZVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMIXdsvGaee3OYq17lJui5KTLIXfGJ-48',
    appId: '1:519139634593:android:ba30717bc8e321a0de2fe0',
    messagingSenderId: '519139634593',
    projectId: 'ieee-cmsb-app',
    storageBucket: 'ieee-cmsb-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTUgrIcD0M7DhpBDoSIYppQTrwXFwPUbc',
    appId: '1:519139634593:web:d32f4fa310750fb0de2fe0',
    messagingSenderId: '519139634593',
    projectId: 'ieee-cmsb-app',
    authDomain: 'ieee-cmsb-app.firebaseapp.com',
    storageBucket: 'ieee-cmsb-app.appspot.com',
    measurementId: 'G-W7R71Q0BLB',
  );
}
